<?php

namespace BackOfficeBundle\Repository;

/**
 * SettingsDevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsDevisRepository extends \Doctrine\ORM\EntityRepository
{
}
